import { type ReactNode } from 'react';
import './markdown.css';

/**
 * Minimal Markdown renderer for the evaluation report.
 *
 * The report is generated by this application, so the grammar it can contain is known
 * and small: headings, bullets, bold, inline code, one pipe table, a horizontal rule,
 * and paragraphs of prose from the executive summary. That makes a 100-line renderer a
 * better trade than a dependency.
 *
 * Output is React elements, never `dangerouslySetInnerHTML` — the executive summary is
 * model-generated text, and it should not be able to inject markup into the page.
 */
export function Markdown({ source }: { source: string }) {
  return <div className="md">{renderBlocks(source)}</div>;
}

function renderBlocks(source: string): ReactNode[] {
  const lines = source.replace(/\r\n/g, '\n').split('\n');
  const blocks: ReactNode[] = [];
  let index = 0;
  let key = 0;

  while (index < lines.length) {
    const line = lines[index];
    const trimmed = line.trim();

    if (!trimmed) {
      index += 1;
      continue;
    }

    // Horizontal rule
    if (/^-{3,}$/.test(trimmed)) {
      blocks.push(<hr key={key++} className="md-rule" />);
      index += 1;
      continue;
    }

    // Heading
    const heading = /^(#{1,4})\s+(.*)$/.exec(trimmed);
    if (heading) {
      const level = heading[1].length;
      const Tag = (['h1', 'h2', 'h3', 'h4'] as const)[level - 1];
      blocks.push(
        <Tag key={key++} className={`md-h${level}`}>
          {inline(heading[2])}
        </Tag>,
      );
      index += 1;
      continue;
    }

    // Pipe table: a header row, a separator row, then body rows.
    if (trimmed.startsWith('|') && /^\|[\s:|-]+\|$/.test((lines[index + 1] ?? '').trim())) {
      const header = splitRow(trimmed);
      const rows: string[][] = [];
      index += 2;
      while (index < lines.length && lines[index].trim().startsWith('|')) {
        rows.push(splitRow(lines[index].trim()));
        index += 1;
      }
      blocks.push(
        <div key={key++} className="md-table-wrap">
          <table className="md-table">
            <thead>
              <tr>
                {header.map((cell, i) => (
                  <th key={i} className={i === 0 ? undefined : 'num'}>
                    {inline(cell)}
                  </th>
                ))}
              </tr>
            </thead>
            <tbody>
              {rows.map((row, r) => (
                <tr key={r}>
                  {row.map((cell, c) => (
                    <td key={c} className={c === 0 ? undefined : 'num'}>
                      {inline(cell)}
                    </td>
                  ))}
                </tr>
              ))}
            </tbody>
          </table>
        </div>,
      );
      continue;
    }

    // Bullet list, including one level of indented sub-items.
    if (/^[-*]\s+/.test(trimmed)) {
      const items: { text: string; depth: number }[] = [];
      while (index < lines.length && /^\s*[-*]\s+/.test(lines[index])) {
        const raw = lines[index];
        const indent = raw.length - raw.trimStart().length;
        items.push({ text: raw.trim().replace(/^[-*]\s+/, ''), depth: indent >= 2 ? 1 : 0 });
        index += 1;
      }
      blocks.push(
        <ul key={key++} className="md-list">
          {items.map((item, i) => (
            <li key={i} data-depth={item.depth}>
              {inline(item.text)}
            </li>
          ))}
        </ul>,
      );
      continue;
    }

    // Paragraph: consume until a blank line or the start of another block.
    const paragraph: string[] = [];
    while (
      index < lines.length &&
      lines[index].trim() &&
      !/^(#{1,4}\s|[-*]\s|\||-{3,}$)/.test(lines[index].trim())
    ) {
      paragraph.push(lines[index].trim());
      index += 1;
    }
    if (paragraph.length) {
      blocks.push(
        <p key={key++} className="md-p">
          {inline(paragraph.join(' '))}
        </p>,
      );
    }
  }

  return blocks;
}

function splitRow(line: string): string[] {
  return line
    .replace(/^\|/, '')
    .replace(/\|$/, '')
    .split('|')
    .map((cell) => cell.trim());
}

/** Render bold, italic and inline code within a line of text. */
function inline(text: string): ReactNode[] {
  const nodes: ReactNode[] = [];
  const pattern = /(\*\*[^*]+\*\*|`[^`]+`|\*[^*]+\*)/g;
  let last = 0;
  let key = 0;
  let match: RegExpExecArray | null;

  while ((match = pattern.exec(text)) !== null) {
    if (match.index > last) nodes.push(text.slice(last, match.index));
    const token = match[0];

    if (token.startsWith('**')) {
      nodes.push(<strong key={key++}>{token.slice(2, -2)}</strong>);
    } else if (token.startsWith('`')) {
      nodes.push(
        <code key={key++} className="md-code">
          {token.slice(1, -1)}
        </code>,
      );
    } else {
      nodes.push(<em key={key++}>{token.slice(1, -1)}</em>);
    }
    last = match.index + token.length;
  }

  if (last < text.length) nodes.push(text.slice(last));
  return nodes;
}
